name: "Build"
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: cachix/cachix-action@v14
        with:
          name: rpi-headless
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: docker/setup-qemu-action@v1
      - run: |
          nix build .#packages.aarch64-linux.sdcard
      - id: commit
        run: |
          echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          # include timestamp and commit hash in the artifact name
          name: rpi-headless-${{ steps.commit.outputs.date }}-${{ steps.commit.outputs.short_sha }}
          path: result/sd-image/*.img.zst
